"""Constants used throughout the OriginChats codebase."""

DEFAULT_MAX_MESSAGE_LENGTH = 2000
DEFAULT_MESSAGES_LIMIT = 50
MAX_MESSAGES_AROUND = 200
MAX_PING_SCAN_MESSAGES = 10000
DEFAULT_SEARCH_RESULTS = 30
DEFAULT_PINGS_LIMIT = 50
MAX_PINGS_LIMIT = 100

DEFAULT_MAX_ATTACHMENT_SIZE = 100 * 1024 * 1024  # 100MB
DEFAULT_WEBHOOK_MAX_BODY_SIZE = 10 * 1024 * 1024  # 10MB

MIN_POLL_OPTIONS = 2
MAX_POLL_OPTIONS = 10

HEARTBEAT_INTERVAL = 30  # seconds

ALLOWED_STATUSES = {"online", "idle", "dnd", "offline", "invisible"}

SYSTEM_ROLES = {"owner", "admin", "moderator", "user"}
PROTECTED_ROLES = {"owner", "admin", "moderator"}

MAX_NICKNAME_LENGTH = 20

FILE_SIZE_SMALL_MB = 5
FILE_SIZE_MEDIUM_MB = 25
FILE_SIZE_LARGE_MB = 100
EXPIRATION_DAYS_SMALL = 49
EXPIRATION_DAYS_MEDIUM = 7
EXPIRATION_DAYS_LARGE = 1

IMAGE_COMPRESSION_ENABLED = True
IMAGE_MAX_WIDTH = 1920
IMAGE_MAX_HEIGHT = 1920
JPEG_QUALITY = 85
WEBP_QUALITY = 85
PNG_COMPRESSION = 6

UNREFERENCED_ATTACHMENT_HOURS = 1
SIX_MONTHS_SECONDS = 6 * 30 * 24 * 60 * 60
