"""Constants used throughout the OriginChats codebase."""

DEFAULT_MAX_ATTACHMENT_SIZE = 100 * 1024 * 1024  # 100MB

HEARTBEAT_INTERVAL = 30  # seconds

ALLOWED_STATUSES = {"online", "idle", "dnd", "offline", "invisible"}

PROTECTED_ROLES = {"owner", "admin", "moderator"}

MAX_NICKNAME_LENGTH = 20

FILE_SIZE_SMALL_MB = 5
FILE_SIZE_MEDIUM_MB = 25
FILE_SIZE_LARGE_MB = 100
EXPIRATION_DAYS_SMALL = 49

IMAGE_MAX_WIDTH = 1920
IMAGE_MAX_HEIGHT = 1920
JPEG_QUALITY = 85
WEBP_QUALITY = 85
PNG_COMPRESSION = 6

UNREFERENCED_ATTACHMENT_HOURS = 1
SIX_MONTHS_SECONDS = 6 * 30 * 24 * 60 * 60
